# Generated by Django 2.1.5 on 2020-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200219_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
