# Generated by Django 2.1.5 on 2020-02-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classroom_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
