# Generated by Django 2.1.5 on 2020-02-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20200219_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
    ]
